### ISSUE TITLE
Bug - Impostor disguised

### ISSUE THREAD

**Issue by MatuxGG** [Hardel-DW/ModsThanos#1]
Hello,

When a meeting is called and an impostor is disguised thanks to the stone, we can see the impostor disguised.

Your mod is awesome btw ;)

![bug](https://user-images.githubusercontent.com/12508157/109403425-d8bb3900-795d-11eb-932d-03dbd33e4374.png)

**Comment by Hardel-DW** [comment]
Yes I have encountered this bug too I will fix it for version 1.3.

**Comment by MatuxGG** [comment]
Nice :)
